language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev gcc-4.8
before_script:
  - export CXX=g++4.8
script:
  - make -C c++11
